project_id = "uvwanpztskkhzdqifbai"

[functions.whatsapp-status-webhook]
verify_jwt = false

[functions.whatsapp-qr-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.create-whatsapp-instance]
verify_jwt = true